openapi: 3.0.0
info:
  title: Customer API
  description: |-
    This is a Customer Server based on the OpenAPI 3.0 specification.
  version: 1.0.11
tags:
  - name: Customers
paths:
  /api/customers:
    post:
      tags:
        - Customers
      summary: Create a new customer object
      description: API for adding new customer objects
      requestBody:
        description: New customer's information
        content:
          application/json:
            schema:
              type: object
              properties:
                firstName:
                  type: string
                  description: The new customer's first name
                lastName:
                  type: string
                  description: The new customer's last name
                username:
                  type: string
                  description: The new customer's username
      responses:
        '200':
          description: Customer added
        '500':
          description: Server exception
        '501':
          description: MongoDB exception
  /api/customers/{username}/invoices:
    post:
      tags:
        - Customers
      summary: Create a new invoice object for a specific customer
      description: API for adding new invoice objects
      parameters:
        - name: username
          in: path
          description: Username of customer creating the invoice.
          required: true
          schema:
            type: string
      requestBody:
        description: Invoice's information
        content:
          application/json:
            schema:
              type: object
              properties:
                subtotal:
                  type: number
                  description: The new invoice's subtotal.
                tax:
                  type: number
                  description: The new invoice's tax amount.
                dateCreated:
                  type: string
                  description: The date the new invoice was created.
                dateShipped:
                  type: string
                  description: The date the invoice was shipped.
                lineItems:
                  type: array
                  description: A list of line items belonging to the new invoice.
                  items:
                    type: object
                    properties:
                      name:
                        type: string
                        description: The line item's name
                      price:
                        type: number
                        description: The line item's price
                      quantity:
                        type: number
                        description: The number of line items purchased
      responses:
          '200':
            description: Customer added
          '500':
            description: Server exception
          '501':
            description: MongoDB exception
    get:
      tags:
        - Customers
      summary: Returns a list of invoices belonging to the customer
      description: API for returning a list of Invoice objects from MongoDB.
      parameters:
        - name: username
          in: path
          description: Username of customer whose invoices are being fetched.
          required: true
          schema:
            type: string
      responses:
          '200':
            description: Customer added
          '500':
            description: Server exception
          '501':
            description: MongoDB exception
