openapi: 3.0.0
info:
  title: Teams API
  description: |-
    This is a Teams Server based on the OpenAPI 3.0 specification.
  version: 1.0.11
tags:
  - name: Teams
paths:
  /api/teams:
    get:
      tags:
        - Teams
      summary: Find all teams.
      description: API for returning a list of teams from MongoDB Atlas.
      responses:
        '200':
          description: Array of team documents
        '500':
          description: Server exception
        '501':
          description: MongoDB exception
  /api/teams/{id}/players:
    post:
      tags:
        - Teams
      summary: Assign a new player to a team.
      description: API for assigning new player objects to a team.
      parameters:
        - name: id
          in: path
          description: The ID of the team in which to assign the new player.
          required: true
          schema:
            type: string
      requestBody:
        description: Player's information
        content:
          application/json:
            schema:
                type: object
                properties:
                  firstName:
                    type: string
                    description: The new player's first name
                  lastName:
                    type: string
                    description: The new player's last name
                  salary:
                    type: number
                    description: The new player's salary
      responses:
        '200':
          description: Player document
        '401':
          description: Invalid teamId
        '500':
          description: Server exception
        '501':
          description: MongoDB exception
    get:
      tags:
        - Teams
      summary: Find All Players by Team ID
      description: API for retrieving a list of player documents for a specified team.
      parameters:
        - name: id
          in: path
          description: The team ID whose players will be retrieved.
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Array of player documents
        '401':
          description: 'Invalid teamId'
        '500':
          description: Server exception
        '501':
          description: MongoDB exception