openapi: 3.0.0
info:
  title: Composer API
  description: |-
    This is a Composer Server based on the OpenAPI 3.0 specification.
  version: 1.0.11
tags:
  - name: Composers
paths:
  /api/composers:
    get:
      tags:
        - Composers
      summary: Returns a list of composer documents
      description: API for returning a list of composers from MongoDB Atlas.
      responses:
        '200':
          description: Composer documents
        '500':
          description: Server exception
        '501':
          description: MongoDB exception
    post:
      tags:
        - Composers
      summary: Create a new composer object
      description: API for adding new composer objects
      requestBody:
        description: Composer's information
        content:
          application/json:
            schema:
                type: object
                properties:
                  firstName:
                    type: string
                    description: The new composer's first name
                  lastName:
                    type: string
                    description: The new composer's last name
      responses:
        '200':
          description: Composer added
        '500':
          description: Server exception
        '501':
          description: MongoDB exception
  /api/composers/{id}:
    get:
      tags:
        - Composers
      summary: Returns a composer document
      description: API for returning a single Composer document from MongoDB.
      parameters:
        - name: id
          in: path
          description: The composerId requested by the user.
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Composer document in JSON format.
        '500':
          description: Server exception
        '501':
          description: MongoDB exception
    put:
      tags:
        - Composers
      summary: Returns an updated composer document
      description: API for updating a single Composer document from MongoDB.
      parameters:
        - name: id
          in: path
          description: The composerId requested by the user.
          required: true
          schema:
            type: string
      requestBody:
        description: The updated first and last name of the composer.
        content:
          application/json:
            schema:
              type: object
              properties:
                firstName:
                  type: string
                lastName:
                  type: string
        required: true
      responses:
        '200':
          description: Array of Composer documents
        '401':
          description: Invalid Composer ID
        '500':
          description: Server exception
        '501':
          description: MongoDB exception
    delete:
      tags:
        - Composers
      summary: Deletes a composer document
      description: API for deleting a single Composer object by their ID.
      parameters:
        - name: id
          in: path
          description: The composerId to delete.
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Composer successfully deleted.
        '500':
          description: Server exception
        '501':
          description: MongoDB exception
          